# Generated by Django 5.2 on 2025-05-12 20:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('actived', models.BooleanField(default=True, verbose_name='Activo')),
                ('installed', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de instalación')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Kit solar',
                'verbose_name_plural': 'Kits solares',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Charge_controller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca del regulador de carga')),
                ('type', models.CharField(max_length=100, verbose_name='Tipo de regulador de carga')),
                ('max_voltage', models.IntegerField(verbose_name='Voltaje máximo del regulador de carga (V)')),
                ('max_amps', models.IntegerField(verbose_name='Amperios máximos del regulador de carga (A)')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de serie del regulador de carga')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charge_controllers', to='kit.kit', verbose_name='Kit solar')),
            ],
            options={
                'verbose_name': 'Regulador de carga',
                'verbose_name_plural': 'Reguladores de carga',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Solar_panel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca del panel')),
                ('type', models.CharField(max_length=100, verbose_name='Tipo de panel')),
                ('watts', models.IntegerField(verbose_name='Potencia del panel (W)')),
                ('voltage', models.IntegerField(verbose_name='Voltaje del panel (V)')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de serie del panel')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solar_panels', to='kit.kit', verbose_name='Kit solar')),
            ],
            options={
                'verbose_name': 'Panel solar',
                'verbose_name_plural': 'Paneles solares',
                'ordering': ['-created'],
            },
        ),
    ]
