# Generated by Django 5.2 on 2025-05-16 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipos_solares', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='charge_controller',
            name='kit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='charge_controller', to='kit.kit', verbose_name='Kit solar'),
        ),
    ]
