# Generated by Django 5.2 on 2025-05-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0002_kit_user_alter_charge_controller_kit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kit',
            old_name='actived',
            new_name='active',
        ),
    ]
