# Generated by Django 5.2 on 2025-05-16 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0003_rename_actived_kit_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='installed',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de instalación'),
        ),
    ]
