# Generated by Django 5.2 on 2025-05-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0004_alter_kit_installed'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='name',
            field=models.CharField(default='default', max_length=100, verbose_name='Nombre del equipo solar'),
            preserve_default=False,
        ),
    ]
