# Generated by Django 5.2 on 2025-05-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0006_alter_kit_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Charge_controller',
            new_name='ChargeController',
        ),
        migrations.RenameModel(
            old_name='Solar_panel',
            new_name='SolarPanel',
        ),
        migrations.AlterModelOptions(
            name='chargecontroller',
            options={},
        ),
        migrations.AlterModelOptions(
            name='kit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='solarpanel',
            options={},
        ),
    ]
