# Generated by Django 5.2 on 2025-05-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0007_rename_charge_controller_chargecontroller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargecontroller',
            name='type',
            field=models.CharField(choices=[('PWM', 'PWM'), ('MPPT', 'MPPT')], max_length=100, verbose_name='Tipo de regulador de carga'),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='type',
            field=models.CharField(choices=[('Monocristalino', 'Monocristalino'), ('Policristalino', 'Policristalino'), ('Amorfo', 'Amorfo'), ('Bifacial', 'Bifacial')], max_length=100, verbose_name='Tipo de panel'),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='voltage',
            field=models.IntegerField(choices=[(12, '12V'), (24, '24V'), (48, '48V')], verbose_name='Voltaje del panel (V)'),
        ),
    ]
