# Generated by Django 5.2 on 2025-05-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0008_alter_chargecontroller_type_alter_solarpanel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargecontroller',
            name='max_amps',
            field=models.PositiveSmallIntegerField(verbose_name='Amperios máximos del regulador de carga (A)'),
        ),
        migrations.AlterField(
            model_name='chargecontroller',
            name='max_voltage',
            field=models.PositiveSmallIntegerField(verbose_name='Voltaje máximo del regulador de carga (V)'),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='voltage',
            field=models.PositiveSmallIntegerField(choices=[(12, '12V'), (24, '24V'), (48, '48V')], verbose_name='Voltaje del panel (V)'),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='watts',
            field=models.PositiveSmallIntegerField(verbose_name='Potencia del panel (W)'),
        ),
    ]
