# Generated by Django 5.2 on 2025-05-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0009_alter_chargecontroller_max_amps_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kit',
            options={'ordering': ['-active', '-installed']},
        ),
        migrations.AlterModelOptions(
            name='solarpanel',
            options={'ordering': ['-created']},
        ),
    ]
