# Generated by Django 5.2 on 2025-05-18 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kit', '0007_rename_charge_controller_chargecontroller_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('yield_wh', models.IntegerField(verbose_name='yield(Wh)')),
                ('consumption', models.IntegerField(verbose_name='consumption(Wh)')),
                ('max_power', models.FloatField(verbose_name='max. PV power(W)')),
                ('max_voltage', models.FloatField(verbose_name='max. PV voltage(V)')),
                ('min_battery_voltage', models.FloatField(verbose_name='min. battery voltage(V)')),
                ('max_battery_voltage', models.FloatField(verbose_name='max. battery voltage(V)')),
                ('bulk_time', models.IntegerField(verbose_name='time in bulk(m)')),
                ('absortion_time', models.IntegerField(verbose_name='time in absorption(m)')),
                ('float_time', models.IntegerField(verbose_name='time in float(m)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='data', to='kit.kit', verbose_name='equipo solar')),
            ],
        ),
    ]
