# Generated by Django 5.2 on 2025-05-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_data_date_alter_data_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='kit',
        ),
    ]
