# Generated by Django 5.2 on 2025-05-18 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_data_kit'),
        ('kit', '0007_rename_charge_controller_chargecontroller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='kit',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, related_name='data', to='kit.kit', verbose_name='equipo solar'),
            preserve_default=False,
        ),
    ]
