# Generated by Django 5.2 on 2025-05-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_data_kit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
