# Generated by Django 5.2 on 2025-05-20 09:04

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='absortion_time',
            field=models.PositiveSmallIntegerField(verbose_name='time in absorption(m)'),
        ),
        migrations.AlterField(
            model_name='data',
            name='bulk_time',
            field=models.PositiveSmallIntegerField(verbose_name='time in bulk(m)'),
        ),
        migrations.AlterField(
            model_name='data',
            name='consumption',
            field=models.PositiveSmallIntegerField(verbose_name='consumption(Wh)'),
        ),
        migrations.AlterField(
            model_name='data',
            name='float_time',
            field=models.PositiveSmallIntegerField(verbose_name='time in float(m)'),
        ),
        migrations.AlterField(
            model_name='data',
            name='max_battery_voltage',
            field=data.models.PositiveFloatField(verbose_name='max. battery voltage(V)'),
        ),
        migrations.AlterField(
            model_name='data',
            name='max_power',
            field=data.models.PositiveFloatField(verbose_name='max. PV power(W)'),
        ),
        migrations.AlterField(
            model_name='data',
            name='max_voltage',
            field=data.models.PositiveFloatField(verbose_name='max. PV voltage(V)'),
        ),
        migrations.AlterField(
            model_name='data',
            name='min_battery_voltage',
            field=data.models.PositiveFloatField(verbose_name='min. battery voltage(V)'),
        ),
        migrations.AlterField(
            model_name='data',
            name='yield_wh',
            field=models.PositiveSmallIntegerField(verbose_name='yield(Wh)'),
        ),
    ]
