# Generated by Django 5.2 on 2025-05-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_data_absortion_time_alter_data_bulk_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['-date']},
        ),
    ]
