# Generated by Django 5.2 on 2025-05-30 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_data_options'),
        ('kit', '0011_alter_chargecontroller_kit_alter_kit_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='kit.kit', verbose_name='equipo solar'),
        ),
    ]
